[phases.setup]
nixPkgs = ["python311Full"]

[phases.install]
cmds = [
  "python -m ensurepip --upgrade",
  "python -m pip install --upgrade pip",
  "python -m pip install poetry==1.8.3",
  "poetry config virtualenvs.create false",
  "poetry install --only main --no-root"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
