"""initial_schema

Revision ID: ded24518b32b
Revises: 
Create Date: 2026-04-14 19:22:35.559475

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ded24518b32b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('razao_social', sa.String(length=150), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=150), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=False, comment='Apenas dígitos, sem formatação'),
    sa.Column('inscricao_estadual', sa.String(length=20), nullable=True),
    sa.Column('inscricao_municipal', sa.String(length=20), nullable=True),
    sa.Column('regime_tributario', sa.String(length=5), nullable=False, comment='SN=Simples Nacional | LP=Lucro Presumido | LR=Lucro Real'),
    sa.Column('end_logradouro', sa.String(length=200), nullable=True),
    sa.Column('end_numero', sa.String(length=10), nullable=True),
    sa.Column('end_complemento', sa.String(length=100), nullable=True),
    sa.Column('end_bairro', sa.String(length=100), nullable=True),
    sa.Column('end_municipio', sa.String(length=100), nullable=True),
    sa.Column('end_uf', sa.CHAR(length=2), nullable=True),
    sa.Column('end_cep', sa.String(length=8), nullable=True, comment='Apenas dígitos, sem formatação'),
    sa.Column('end_codigo_ibge', sa.String(length=7), nullable=True, comment='Código IBGE do município para NF-e'),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('ambiente_fiscal', sa.String(length=1), nullable=False, comment='1=Produção | 2=Homologação. Iniciar sempre em Homologação.'),
    sa.Column('serie_nfce', sa.Integer(), nullable=False, comment='Série padrão da NFC-e (geralmente 1). Numeração em sequencias_fiscais.'),
    sa.Column('serie_nfe', sa.Integer(), nullable=False, comment='Série padrão da NF-e. Numeração em sequencias_fiscais.'),
    sa.Column('csc_id_producao', sa.String(length=6), nullable=True, comment='ID do CSC em ambiente de Produção'),
    sa.Column('csc_token_producao', sa.String(length=36), nullable=True, comment='Token CSC em ambiente de Produção'),
    sa.Column('csc_id_homologacao', sa.String(length=6), nullable=True),
    sa.Column('csc_token_homologacao', sa.String(length=36), nullable=True),
    sa.Column('fiscal_provider_nome', sa.String(length=50), nullable=True, comment='Ex: focus_nfe | plugnotas'),
    sa.Column('fiscal_provider_api_key', sa.String(length=500), nullable=True, comment='Chave de API — armazenada criptografada pela camada de serviço'),
    sa.Column('fiscal_provider_cnpj_emissor', sa.String(length=14), nullable=True, comment='CNPJ registrado no provedor fiscal (pode diferir do CNPJ principal em testes)'),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj', name='uq_empresas_cnpj'),
    comment='Configuração central da empresa e parâmetros fiscais'
    )
    op.create_table('caixas',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False, comment='Número sequencial do caixa na loja (1, 2, 3...)'),
    sa.Column('descricao', sa.String(length=100), nullable=True, comment="Ex: 'Caixa Principal', 'Caixa Rápido'"),
    sa.Column('numero_serie', sa.String(length=50), nullable=True, comment='Número de série do terminal, exigido por alguns estados para NFC-e'),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'id', name='uq_caixas_empresa_id'),
    sa.UniqueConstraint('empresa_id', 'numero', name='uq_caixas_numero'),
    comment='Terminal de caixa físico — hardware onde roda o PDV'
    )
    op.create_index('ix_caixas_empresa_id', 'caixas', ['empresa_id'], unique=False)
    op.create_table('categorias',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria_pai_id', sa.UUID(), nullable=True, comment='NULL = categoria raiz'),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categoria_pai_id'], ['categorias.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nome', 'categoria_pai_id', name='uq_categorias_nome'),
    comment='Categorias hierárquicas de produtos (máx. 3 níveis recomendados)'
    )
    op.create_index('ix_categorias_empresa_id', 'categorias', ['empresa_id'], unique=False)
    op.create_table('locais_estoque',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False, comment="Código do local: 'LOJA', 'DEPOSITO', 'FILIAL_SP'"),
    sa.Column('descricao', sa.String(length=100), nullable=False, comment='Ex: Loja Principal, Depósito Fundo, Filial São Paulo'),
    sa.Column('principal', sa.Boolean(), nullable=False, comment='Local principal da empresa — padrão para vendas sem especificação'),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_locais_estoque_codigo'),
    sa.UniqueConstraint('empresa_id', 'id', name='uq_locais_estoque_empresa_id'),
    comment='Locais físicos de estoque: loja, depósito, filial. Cada empresa deve ter um local principal.'
    )
    op.create_index('ix_locais_estoque_empresa_id', 'locais_estoque', ['empresa_id'], unique=False)
    op.create_table('perfis_tributarios',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False, comment="Nome descritivo do perfil, ex: 'Alimentos - Simples Nacional'"),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='Apenas um perfil com o mesmo nome deve estar ativo por vez'),
    sa.Column('vigencia_inicio', sa.Date(), nullable=False, comment='Data de início de vigência deste perfil'),
    sa.Column('vigencia_fim', sa.Date(), nullable=True, comment='Data de fim de vigência. NULL = ainda vigente.'),
    sa.Column('ncm', sa.String(length=8), nullable=False, comment='Nomenclatura Comum do Mercosul — 8 dígitos obrigatórios'),
    sa.Column('cest', sa.String(length=7), nullable=True, comment='Código de Especificação da Substituição Tributária. Obrigatório quando há ST.'),
    sa.Column('origem', sa.String(length=1), nullable=False, comment='Origem da mercadoria conforme tabela de origem do MOC'),
    sa.Column('cfop_saida_interna', sa.String(length=4), nullable=False, comment='CFOP para vendas dentro do estado — geralmente 5102, 5405'),
    sa.Column('cfop_saida_interestadual', sa.String(length=4), nullable=True, comment='CFOP para vendas para outros estados — geralmente 6102, 6404'),
    sa.Column('csosn', sa.String(length=3), nullable=True, comment='Código Situação da Operação Simples Nacional. Valores: 101,102,103,201,202,203,300,400,500,900'),
    sa.Column('cst_icms', sa.String(length=3), nullable=True, comment='CST ICMS: 00,10,20,30,40,41,50,51,60,70,90'),
    sa.Column('modalidade_bc_icms', sa.String(length=1), nullable=True, comment='Modalidade de determinação da BC do ICMS'),
    sa.Column('aliq_icms', sa.Numeric(precision=7, scale=4), nullable=True, comment='Alíquota ICMS em percentual, ex: 12.0000'),
    sa.Column('reducao_bc_icms', sa.Numeric(precision=7, scale=4), nullable=True, comment='Percentual de redução da base de cálculo do ICMS'),
    sa.Column('modalidade_bc_icms_st', sa.String(length=1), nullable=True),
    sa.Column('margem_valor_agregado_icms_st', sa.Numeric(precision=7, scale=4), nullable=True, comment='MVA — Margem de Valor Agregado para ICMS-ST em percentual'),
    sa.Column('reducao_bc_icms_st', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('aliq_icms_st', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('codigo_beneficio_fiscal', sa.String(length=10), nullable=True, comment='Código de benefício fiscal estadual, quando aplicável'),
    sa.Column('cst_pis', sa.String(length=2), nullable=False, comment='CST PIS: 01,02,04,05,06,07,08,49,50,51,99'),
    sa.Column('aliq_pis', sa.Numeric(precision=7, scale=4), nullable=False, comment='Alíquota PIS em percentual. 0 quando isento/não tributado.'),
    sa.Column('cst_cofins', sa.String(length=2), nullable=False, comment='CST COFINS — mesmos valores do CST PIS'),
    sa.Column('aliq_cofins', sa.Numeric(precision=7, scale=4), nullable=False, comment='Alíquota COFINS em percentual'),
    sa.Column('cst_ipi', sa.String(length=2), nullable=True, comment='CST IPI: 00,01,02,03,04,05,49,50,51,52,53,54,55,99'),
    sa.Column('aliq_ipi', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('codigo_enquadramento_ipi', sa.String(length=3), nullable=True, comment='Código de Enquadramento do IPI — tabela TIPI'),
    sa.Column('unidade_tributavel', sa.String(length=6), nullable=True, comment='Unidade tributável quando diferente da unidade comercial'),
    sa.Column('fator_conversao', sa.Numeric(precision=10, scale=4), nullable=True, comment='Fator de conversão entre unidade comercial e tributável'),
    sa.Column('ean_tributavel', sa.String(length=14), nullable=True, comment='EAN da embalagem tributável quando diferente do produto'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(csosn IS NULL) OR (cst_icms IS NULL)', name='ck_perfil_trib_icms_exclusivo'),
    sa.CheckConstraint('ativo = false OR vigencia_fim IS NULL', name='ck_perfil_trib_ativo_sem_fim'),
    sa.CheckConstraint('vigencia_fim IS NULL OR vigencia_fim > vigencia_inicio', name='ck_perfil_trib_vigencia_valida'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Perfis fiscais versionados por produto'
    )
    op.create_index('ix_perfil_trib_empresa_ativo', 'perfis_tributarios', ['empresa_id', 'ativo'], unique=False)
    op.create_index('ix_perfil_trib_ncm', 'perfis_tributarios', ['ncm'], unique=False)
    op.create_index('uq_perfil_tributario_nome_ativo', 'perfis_tributarios', ['empresa_id', 'nome'], unique=True, postgresql_where=sa.text('ativo = true'))
    op.create_table('sequencias_fiscais',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=5), nullable=False, comment="Tipo do documento: 'nfce' | 'nfe' | 'sat'"),
    sa.Column('serie', sa.Integer(), nullable=False, comment='Número da série fiscal (geralmente 1)'),
    sa.Column('proximo_numero', sa.Integer(), nullable=False, comment='Próximo número a ser emitido. Incrementar via SELECT FOR UPDATE.'),
    sa.Column('ultimo_numero_emitido', sa.Integer(), nullable=True, comment='Último número efetivamente autorizado pela SEFAZ (para diagnóstico)'),
    sa.Column('ultimo_numero_inutilizado', sa.Integer(), nullable=True, comment='Último número inutilizado (faixa com falha não recuperável)'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo IN ('nfce', 'nfe', 'sat')", name='ck_sequencia_tipo_valido'),
    sa.CheckConstraint('proximo_numero >= 1', name='ck_sequencia_numero_positivo'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('empresa_id', 'tipo', 'serie'),
    sa.UniqueConstraint('empresa_id', 'tipo', 'serie', name='uq_sequencias_fiscais'),
    comment='Controle transacional de numeração fiscal. SEMPRE usar SELECT FOR UPDATE ao ler e incrementar.'
    )
    op.create_index('ix_sequencias_fiscais_empresa_id', 'sequencias_fiscais', ['empresa_id'], unique=False)
    op.create_table('unidades_medida',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=6), nullable=False, comment='Código padrão: UN, KG, G, LT, ML, CX, DZ, PCT'),
    sa.Column('descricao', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('casas_decimais', sa.Integer(), nullable=False, comment='0 para unitário, 3 para pesável (kg com 3 casas)'),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', name='uq_unidades_medida_codigo'),
    comment='Unidades de medida comercial: UN, KG, LT, CX, DZ, etc.'
    )
    op.create_index('ix_unidades_medida_empresa_id', 'unidades_medida', ['empresa_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False, comment='Hash bcrypt — custo mínimo 12'),
    sa.Column('perfil', sa.String(length=20), nullable=False, comment='Perfil de acesso que define permissões base'),
    sa.Column('codigo_operador', sa.String(length=20), nullable=True, comment='Código curto para login rápido no PDV (numérico, ex: 001)'),
    sa.Column('pin_hash', sa.String(length=200), nullable=True, comment='PIN de 4-6 dígitos para login rápido no caixa (bcrypt)'),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo_operador', name='uq_usuarios_empresa_codigo_operador'),
    sa.UniqueConstraint('empresa_id', 'email', name='uq_usuarios_empresa_email'),
    comment='Operadores, gerentes e administradores do sistema'
    )
    op.create_index('ix_usuarios_email', 'usuarios', ['email'], unique=False)
    op.create_index('ix_usuarios_empresa_id', 'usuarios', ['empresa_id'], unique=False)
    op.create_table('produtos',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True, comment='Stock Keeping Unit — código interno do produto'),
    sa.Column('codigo_barras_principal', sa.String(length=14), nullable=True, comment='EAN-13 ou DUN-14 principal. Demais EANs em produto_eans.'),
    sa.Column('descricao', sa.String(length=200), nullable=False, comment='Descrição completa para NF-e / cadastro'),
    sa.Column('descricao_pdv', sa.String(length=60), nullable=True, comment='Descrição curta exibida no PDV e no recibo (≤60 chars)'),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('unidade_id', sa.UUID(), nullable=False),
    sa.Column('pesavel', sa.Boolean(), nullable=False, comment='True = produto vendido por peso (balança). Preço por kg.'),
    sa.Column('balanca_codigo', sa.Integer(), nullable=True, comment='Código PLU para balança integrada (1-5 dígitos)'),
    sa.Column('preco_venda', sa.Numeric(precision=15, scale=4), nullable=False, comment='Preço de venda atual em R$'),
    sa.Column('custo_medio', sa.Numeric(precision=15, scale=4), nullable=False, comment='Custo médio ponderado, atualizado a cada entrada de estoque'),
    sa.Column('margem_calculada', sa.Numeric(precision=7, scale=4), nullable=True, comment='Margem bruta em % — snapshot calculado. Não usar como fonte primária.'),
    sa.Column('estoque_minimo', sa.Numeric(precision=15, scale=3), nullable=False, comment='Quantidade mínima de estoque para alerta de ruptura'),
    sa.Column('controla_estoque', sa.Boolean(), nullable=False, comment='False = produto de serviço ou que não controla estoque'),
    sa.Column('perfil_tributario_id', sa.UUID(), nullable=True, comment='Perfil tributário ativo. Sempre referenciar a versão vigente.'),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('destaque_pdv', sa.Boolean(), nullable=False, comment='Exibir como produto em destaque na tela do PDV'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ativo = false OR perfil_tributario_id IS NOT NULL', name='ck_produto_ativo_requer_fiscal'),
    sa.CheckConstraint('custo_medio >= 0', name='ck_produtos_custo_positivo'),
    sa.CheckConstraint('estoque_minimo >= 0', name='ck_produtos_estoque_minimo_positivo'),
    sa.CheckConstraint('preco_venda >= 0', name='ck_produtos_preco_positivo'),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['perfil_tributario_id'], ['perfis_tributarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades_medida.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo_barras_principal', name='uq_produtos_ean'),
    sa.UniqueConstraint('empresa_id', 'sku', name='uq_produtos_sku'),
    comment='Catálogo de produtos com dados comerciais e fiscais'
    )
    op.create_index('ix_produtos_ativo', 'produtos', ['empresa_id', 'ativo'], unique=False)
    op.create_index('ix_produtos_categoria_id', 'produtos', ['categoria_id'], unique=False)
    op.create_index('ix_produtos_ean_principal', 'produtos', ['codigo_barras_principal'], unique=False)
    op.create_index('ix_produtos_empresa_id', 'produtos', ['empresa_id'], unique=False)
    op.create_table('sessoes_caixa',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('caixa_id', sa.UUID(), nullable=False),
    sa.Column('operador_id', sa.UUID(), nullable=False, comment='Operador que abriu o caixa'),
    sa.Column('operador_fechamento_id', sa.UUID(), nullable=True, comment='Operador que fechou o caixa (pode ser diferente do que abriu)'),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('data_abertura', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_fechamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('saldo_abertura', sa.Numeric(precision=15, scale=4), nullable=False, comment='Valor em dinheiro colocado no caixa na abertura (fundo de troco)'),
    sa.Column('saldo_informado_fechamento', sa.Numeric(precision=15, scale=4), nullable=True, comment='Valor que o operador diz ter no caixa ao fechar (contagem física)'),
    sa.Column('saldo_sistema_fechamento', sa.Numeric(precision=15, scale=4), nullable=True, comment='Valor esperado pelo sistema: abertura + entradas - saídas em dinheiro'),
    sa.Column('diferenca_fechamento', sa.Numeric(precision=15, scale=4), nullable=True, comment='Quebra: saldo_informado - saldo_sistema. Negativo = falta.'),
    sa.Column('total_vendas_bruto', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_cancelamentos', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_descontos', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_liquido', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_sangrias', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_suprimentos', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_dinheiro', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_pix', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_cartao_debito', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_cartao_credito', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_outros', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('quantidade_vendas', sa.Integer(), nullable=True),
    sa.Column('ticket_medio', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('observacao_fechamento', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['caixa_id'], ['caixas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id', 'caixa_id'], ['caixas.empresa_id', 'caixas.id'], name='fk_sessoes_caixa_empresa_caixa', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operador_fechamento_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operador_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'id', name='uq_sessoes_caixa_empresa_id'),
    comment='Sessão/turno de operação do caixa com conferência ao fechamento'
    )
    op.create_index('ix_sessoes_caixa_abertura', 'sessoes_caixa', ['data_abertura'], unique=False)
    op.create_index('ix_sessoes_caixa_caixa_id', 'sessoes_caixa', ['caixa_id'], unique=False)
    op.create_index('ix_sessoes_caixa_operador_id', 'sessoes_caixa', ['operador_id'], unique=False)
    op.create_index('ix_sessoes_caixa_status', 'sessoes_caixa', ['empresa_id', 'status'], unique=False)
    op.create_index('uq_sessao_caixa_aberta', 'sessoes_caixa', ['caixa_id'], unique=True, postgresql_where=sa.text("status = 'aberta'"))
    op.create_table('estoque',
    sa.Column('produto_id', sa.UUID(), nullable=False, comment='Componente da PK composta'),
    sa.Column('local_estoque_id', sa.UUID(), nullable=False, comment='Componente da PK composta — local físico de armazenamento'),
    sa.Column('empresa_id', sa.UUID(), nullable=False, comment='Desnormalizado para queries por empresa sem JOIN'),
    sa.Column('saldo_atual', sa.Numeric(precision=15, scale=3), nullable=False, comment='Saldo atual em unidades ou kg.'),
    sa.Column('saldo_reservado', sa.Numeric(precision=15, scale=3), nullable=False, comment='Quantidade reservada para vendas em andamento (uso futuro)'),
    sa.Column('permite_negativo', sa.Boolean(), nullable=False, comment='Permite saldo negativo neste local. Depósito pode aceitar para recebimentos antecipados; loja geralmente não.'),
    sa.Column('versao', sa.Integer(), nullable=False, comment='Versão para controle otimista de concorrência. Incrementar em cada UPDATE.'),
    sa.Column('principal', sa.Boolean(), nullable=False, comment='True = este local é o estoque principal do produto (leitura rápida no PDV)'),
    sa.Column('ultima_entrada', sa.DateTime(timezone=True), nullable=True, comment='Data/hora da última entrada de estoque'),
    sa.Column('ultima_saida', sa.DateTime(timezone=True), nullable=True, comment='Data/hora da última saída de estoque'),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('saldo_atual >= 0 OR permite_negativo = true', name='ck_estoque_saldo_politica_negativo'),
    sa.CheckConstraint('saldo_reservado >= 0', name='ck_estoque_saldo_reservado_positivo'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['local_estoque_id'], ['locais_estoque.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('produto_id', 'local_estoque_id'),
    comment='Saldo atual de estoque por produto e local — atualizado atomicamente'
    )
    op.create_index('ix_estoque_empresa_id', 'estoque', ['empresa_id'], unique=False)
    op.create_index('ix_estoque_local_id', 'estoque', ['local_estoque_id'], unique=False)
    op.create_index('ix_estoque_saldo_baixo', 'estoque', ['empresa_id', 'saldo_atual'], unique=False)
    op.create_table('log_auditoria',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True, comment='NULL = ação do sistema (automação, scheduler, etc.)'),
    sa.Column('acao', sa.String(length=100), nullable=False, comment="Código da ação auditada. Ex: 'venda.cancelar', 'produto.alterar_preco', 'caixa.sangria', 'usuario.alterar_senha'"),
    sa.Column('tabela_afetada', sa.String(length=60), nullable=True, comment='Nome da tabela do banco afetada pela operação'),
    sa.Column('registro_id', sa.UUID(), nullable=True, comment='UUID do registro afetado na tabela'),
    sa.Column('dados_anteriores', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Estado do registro ANTES da operação (snapshot)'),
    sa.Column('dados_novos', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Estado do registro APÓS a operação (snapshot)'),
    sa.Column('descricao', sa.Text(), nullable=True, comment='Descrição legível da ação para exibição no relatório de auditoria'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP do cliente (IPv4 ou IPv6)'),
    sa.Column('user_agent', sa.String(length=300), nullable=True, comment='User-Agent do browser/app (para diagnóstico)'),
    sa.Column('sessao_caixa_id', sa.UUID(), nullable=True, comment='Sessão do caixa ativa quando a ação foi realizada'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sessao_caixa_id'], ['sessoes_caixa.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Trilha de auditoria imutável de todas as operações sensíveis'
    )
    op.create_index('ix_log_auditoria_acao', 'log_auditoria', ['empresa_id', 'acao'], unique=False)
    op.create_index('ix_log_auditoria_criado_em', 'log_auditoria', ['criado_em'], unique=False)
    op.create_index('ix_log_auditoria_empresa_id', 'log_auditoria', ['empresa_id'], unique=False)
    op.create_index('ix_log_auditoria_tabela_registro', 'log_auditoria', ['tabela_afetada', 'registro_id'], unique=False)
    op.create_index('ix_log_auditoria_usuario_id', 'log_auditoria', ['usuario_id'], unique=False)
    op.create_table('movimentacoes_caixa',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('sessao_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False, comment='Operador que realizou a sangria/suprimento'),
    sa.Column('autorizado_por_id', sa.UUID(), nullable=True, comment='Gerente/supervisor que autorizou (para sangrias acima de limites)'),
    sa.Column('tipo', sa.String(length=15), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valor > 0', name='ck_mov_caixa_valor_positivo'),
    sa.ForeignKeyConstraint(['autorizado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id', 'sessao_id'], ['sessoes_caixa.empresa_id', 'sessoes_caixa.id'], name='fk_mov_caixa_empresa_sessao', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessoes_caixa.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Sangrias e suprimentos rastreáveis por operador'
    )
    op.create_index('ix_mov_caixa_criado_em', 'movimentacoes_caixa', ['criado_em'], unique=False)
    op.create_index('ix_mov_caixa_sessao_id', 'movimentacoes_caixa', ['sessao_id'], unique=False)
    op.create_table('movimentacoes_estoque',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('local_estoque_id', sa.UUID(), nullable=True, comment='Local físico onde ocorreu a movimentação. NULL = local padrão.'),
    sa.Column('usuario_id', sa.UUID(), nullable=True, comment='Operador responsável. NULL = movimentação automática do sistema.'),
    sa.Column('tipo', sa.String(length=35), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=3), nullable=False, comment='Quantidade movimentada. Sempre positivo — o tipo indica direção.'),
    sa.Column('saldo_anterior', sa.Numeric(precision=15, scale=3), nullable=False, comment='Saldo antes da movimentação — snapshot para auditoria'),
    sa.Column('saldo_posterior', sa.Numeric(precision=15, scale=3), nullable=False, comment='Saldo após a movimentação — snapshot para auditoria'),
    sa.Column('custo_unitario', sa.Numeric(precision=15, scale=4), nullable=True, comment='Custo unitário do produto no momento da movimentação'),
    sa.Column('referencia_tipo', sa.String(length=30), nullable=True, comment="Tipo da entidade que originou: 'venda', 'compra', 'ajuste_manual', 'inventario'"),
    sa.Column('referencia_id', sa.UUID(), nullable=True, comment='UUID da entidade de origem. Não é FK para suportar múltiplas origens.'),
    sa.Column('motivo', sa.Text(), nullable=True, comment='Justificativa textual para ajustes manuais e inventários'),
    sa.Column('documento_fiscal', sa.String(length=100), nullable=True, comment='Número/chave do documento fiscal de entrada (NF-e de compra)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['local_estoque_id'], ['locais_estoque.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Ledger imutável de todas as movimentações de estoque'
    )
    op.create_index('ix_mov_estoque_criado_em', 'movimentacoes_estoque', ['criado_em'], unique=False)
    op.create_index('ix_mov_estoque_empresa_id', 'movimentacoes_estoque', ['empresa_id'], unique=False)
    op.create_index('ix_mov_estoque_local_id', 'movimentacoes_estoque', ['local_estoque_id'], unique=False)
    op.create_index('ix_mov_estoque_produto_data', 'movimentacoes_estoque', ['produto_id', 'criado_em'], unique=False)
    op.create_index('ix_mov_estoque_produto_id', 'movimentacoes_estoque', ['produto_id'], unique=False)
    op.create_index('ix_mov_estoque_referencia', 'movimentacoes_estoque', ['referencia_tipo', 'referencia_id'], unique=False)
    op.create_table('produto_eans',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('ean', sa.String(length=14), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=True, comment="Ex: 'Caixa com 12 unidades', 'Embalagem promocional'"),
    sa.Column('fator_quantidade', sa.Numeric(precision=10, scale=4), nullable=False, comment='Quantas unidades do produto este EAN representa. Ex: 12 para caixa.'),
    sa.Column('principal', sa.Boolean(), nullable=False, comment='EAN principal exibido no cadastro (redundância com produto.codigo_barras_principal)'),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'ean', name='uq_produto_eans_ean'),
    comment='EANs alternativos associados ao produto (leitura de barcode)'
    )
    op.create_index('ix_produto_eans_ean', 'produto_eans', ['ean'], unique=False)
    op.create_index('ix_produto_eans_produto_id', 'produto_eans', ['produto_id'], unique=False)
    op.create_table('vendas',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('sessao_caixa_id', sa.UUID(), nullable=False),
    sa.Column('operador_id', sa.UUID(), nullable=False),
    sa.Column('numero_venda_local', sa.Integer(), nullable=False, comment='Número sequencial da venda no turno — gerado no PDV, exibido no recibo'),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('data_venda', sa.DateTime(timezone=True), nullable=False, comment='Data/hora da venda conforme relógio do PDV (pode ser offline)'),
    sa.Column('total_bruto', sa.Numeric(precision=15, scale=4), nullable=False, comment='Soma dos subtotais dos itens sem descontos'),
    sa.Column('total_desconto', sa.Numeric(precision=15, scale=4), nullable=False, comment='Total de descontos aplicados'),
    sa.Column('total_liquido', sa.Numeric(precision=15, scale=4), nullable=False, comment='Valor final da venda: total_bruto - total_desconto'),
    sa.Column('total_custo', sa.Numeric(precision=15, scale=4), nullable=True, comment='Custo total dos produtos vendidos — para cálculo de margem'),
    sa.Column('cancelada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelada_por_id', sa.UUID(), nullable=True),
    sa.Column('motivo_cancelamento', sa.Text(), nullable=True),
    sa.Column('sincronizada', sa.Boolean(), nullable=False, comment='False = venda criada offline, ainda não confirmada pelo servidor'),
    sa.Column('data_sinc', sa.DateTime(timezone=True), nullable=True, comment='Data/hora em que a venda offline foi sincronizada'),
    sa.Column('origem_pdv', sa.String(length=50), nullable=True, comment='Identificador do terminal PDV de origem (para raástreio offline)'),
    sa.Column('chave_idempotencia', sa.UUID(), nullable=True, comment='UUID gerado pelo PDV para garantir idempotência na sincronização. Impede duplicação de venda offline mesmo em retry.'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_liquido >= 0', name='ck_vendas_total_positivo'),
    sa.ForeignKeyConstraint(['cancelada_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id', 'sessao_caixa_id'], ['sessoes_caixa.empresa_id', 'sessoes_caixa.id'], name='fk_vendas_empresa_sessao_caixa', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operador_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sessao_caixa_id'], ['sessoes_caixa.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave_idempotencia'),
    sa.UniqueConstraint('empresa_id', 'id', name='uq_vendas_empresa_id'),
    sa.UniqueConstraint('sessao_caixa_id', 'numero_venda_local', name='uq_vendas_numero_local_por_sessao'),
    comment='Registro de vendas — suporte offline-first com UUID gerado no cliente'
    )
    op.create_index('ix_vendas_data_venda', 'vendas', ['empresa_id', 'data_venda'], unique=False)
    op.create_index('ix_vendas_empresa_id', 'vendas', ['empresa_id'], unique=False)
    op.create_index('ix_vendas_operador_id', 'vendas', ['operador_id'], unique=False)
    op.create_index('ix_vendas_sessao_caixa_id', 'vendas', ['sessao_caixa_id'], unique=False)
    op.create_index('ix_vendas_status', 'vendas', ['empresa_id', 'status'], unique=False)
    op.create_table('documentos_fiscais',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('venda_id', sa.UUID(), nullable=True, comment='NULL possível em caso de inutilização'),
    sa.Column('operador_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.String(length=5), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True, comment='Número sequencial da NF-e/NFC-e'),
    sa.Column('serie', sa.Integer(), nullable=True, comment='Série da NF-e/NFC-e'),
    sa.Column('chave_acesso', sa.String(length=44), nullable=True, comment='Chave de acesso de 44 dígitos — identificação única na SEFAZ'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ambiente', sa.String(length=1), nullable=False),
    sa.Column('tentativas', sa.Integer(), nullable=False, comment='Número de tentativas de envio ao provedor'),
    sa.Column('proxima_tentativa_em', sa.DateTime(timezone=True), nullable=True, comment='Quando reagendar o próximo reprocessamento (backoff exponencial)'),
    sa.Column('data_emissao', sa.DateTime(timezone=True), nullable=True, comment='Data/hora de emissão conforme informado ao provedor'),
    sa.Column('data_autorizacao', sa.DateTime(timezone=True), nullable=True, comment='Data/hora da autorização pela SEFAZ'),
    sa.Column('protocolo_autorizacao', sa.String(length=20), nullable=True, comment='nProt — número do protocolo de autorização da SEFAZ'),
    sa.Column('codigo_retorno', sa.String(length=6), nullable=True, comment='cStat — código de status da SEFAZ (100=autorizado, 302=dup, etc.)'),
    sa.Column('mensagem_retorno', sa.Text(), nullable=True, comment='xMotivo — descrição do retorno da SEFAZ'),
    sa.Column('em_contingencia', sa.Boolean(), nullable=False, comment='True = emitido em modo offline/contingência, aguardando SEFAZ'),
    sa.Column('tipo_contingencia', sa.String(length=5), nullable=True, comment='FS-DA (Formulário Segurança), EPEC, SVC-AN, SVC-RS'),
    sa.Column('data_entrada_contingencia', sa.DateTime(timezone=True), nullable=True),
    sa.Column('justificativa_contingencia', sa.String(length=256), nullable=True, comment='Texto obrigatório para justificar a contingência no XML'),
    sa.Column('cancelada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('protocolo_cancelamento', sa.String(length=20), nullable=True),
    sa.Column('motivo_cancelamento', sa.Text(), nullable=True, comment='xJust — justificativa de cancelamento (mínimo 15 chars, SEFAZ)'),
    sa.Column('xml_enviado', sa.Text(), nullable=True, comment='XML completo enviado ao provedor fiscal'),
    sa.Column('xml_retorno', sa.Text(), nullable=True, comment='XML de retorno/autorização da SEFAZ (com protocolo)'),
    sa.Column('xml_cancelamento', sa.Text(), nullable=True, comment='XML de evento de cancelamento autorizado'),
    sa.Column('url_danfe', sa.String(length=500), nullable=True, comment='URL do DANFE/DANFCe PDF gerado pelo provedor'),
    sa.Column('url_qrcode', sa.String(length=1000), nullable=True, comment='URL do QR Code para NFC-e'),
    sa.Column('url_consulta_nfe', sa.String(length=200), nullable=True, comment='URL de consulta do NFC-e site governamental'),
    sa.Column('provider_id', sa.String(length=100), nullable=True, comment='ID do documento no sistema do provedor (Focus NFe, PlugNotas, etc.)'),
    sa.Column('provider_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Dados extras retornados pelo provedor (para troubleshooting)'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id', 'venda_id'], ['vendas.empresa_id', 'vendas.id'], name='fk_doc_fiscal_empresa_venda', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operador_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave_acesso', name='uq_doc_fiscal_chave_acesso'),
    comment='Documentos fiscais emitidos via provedor externo (NFC-e, NF-e)'
    )
    op.create_index('ix_doc_fiscal_chave_acesso', 'documentos_fiscais', ['chave_acesso'], unique=False)
    op.create_index('ix_doc_fiscal_data_emissao', 'documentos_fiscais', ['empresa_id', 'data_emissao'], unique=False)
    op.create_index('ix_doc_fiscal_empresa_id', 'documentos_fiscais', ['empresa_id'], unique=False)
    op.create_index('ix_doc_fiscal_pendentes', 'documentos_fiscais', ['status', 'tentativas'], unique=False)
    op.create_index('ix_doc_fiscal_status', 'documentos_fiscais', ['empresa_id', 'status'], unique=False)
    op.create_index('ix_doc_fiscal_venda_id', 'documentos_fiscais', ['venda_id'], unique=False)
    op.create_index('uq_doc_fiscal_venda_ativo', 'documentos_fiscais', ['venda_id'], unique=True, postgresql_where=sa.text("venda_id IS NOT NULL AND status NOT IN ('cancelada', 'rejeitada', 'inutilizada', 'erro')"))
    op.create_table('itens_venda',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('venda_id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('perfil_tributario_id', sa.UUID(), nullable=True),
    sa.Column('descricao_produto', sa.String(length=200), nullable=False, comment='Snapshot da descrição do produto no momento da venda'),
    sa.Column('codigo_barras', sa.String(length=14), nullable=True, comment='Snapshot do EAN usado para bipar o produto'),
    sa.Column('unidade', sa.String(length=6), nullable=True, comment='Snapshot do código da unidade de medida'),
    sa.Column('sequencia', sa.Integer(), nullable=False, comment='Ordem dos itens na venda (começa em 1)'),
    sa.Column('quantidade', sa.Numeric(precision=15, scale=3), nullable=False, comment='Quantidade com 3 casas para produtos pesáveis'),
    sa.Column('preco_unitario', sa.Numeric(precision=15, scale=4), nullable=False, comment='Preço unitário no momento da venda (snapshot)'),
    sa.Column('custo_unitario', sa.Numeric(precision=15, scale=4), nullable=True, comment='Custo médio no momento da venda (para margem histórica)'),
    sa.Column('desconto_unitario', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('total_item', sa.Numeric(precision=15, scale=4), nullable=False, comment='(preco_unitario - desconto_unitario) * quantidade'),
    sa.Column('ncm', sa.String(length=8), nullable=True, comment='NCM snapshot — obrigatório na NF-e'),
    sa.Column('cest', sa.String(length=7), nullable=True),
    sa.Column('cfop', sa.String(length=4), nullable=True, comment='CFOP vigente para a operação no momento da venda'),
    sa.Column('origem', sa.String(length=1), nullable=True),
    sa.Column('csosn', sa.String(length=3), nullable=True, comment='CSOSN (Simples Nacional)'),
    sa.Column('cst_icms', sa.String(length=3), nullable=True, comment='CST ICMS (Lucro Presumido/Real)'),
    sa.Column('aliq_icms', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('cst_pis', sa.String(length=2), nullable=True),
    sa.Column('aliq_pis', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('cst_cofins', sa.String(length=2), nullable=True),
    sa.Column('aliq_cofins', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('snapshot_fiscal', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Snapshot completo do PerfilTributario no momento da venda'),
    sa.Column('cancelado', sa.Boolean(), nullable=False),
    sa.Column('cancelado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelado_por_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('snapshot_fiscal IS NOT NULL OR (ncm IS NOT NULL AND cfop IS NOT NULL AND cst_pis IS NOT NULL AND cst_cofins IS NOT NULL AND (csosn IS NOT NULL OR cst_icms IS NOT NULL))', name='ck_item_venda_fiscal_minimo'),
    sa.ForeignKeyConstraint(['cancelado_por_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id', 'venda_id'], ['vendas.empresa_id', 'vendas.id'], name='fk_itens_venda_empresa_venda', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['perfil_tributario_id'], ['perfis_tributarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Itens de venda com snapshot fiscal imutável'
    )
    op.create_index('ix_itens_venda_produto_data', 'itens_venda', ['produto_id', 'criado_em'], unique=False)
    op.create_index('ix_itens_venda_produto_id', 'itens_venda', ['produto_id'], unique=False)
    op.create_index('ix_itens_venda_venda_id', 'itens_venda', ['venda_id'], unique=False)
    op.create_table('pagamentos_venda',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('venda_id', sa.UUID(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=2), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=4), nullable=False, comment='Valor pago nesta forma de pagamento'),
    sa.Column('troco', sa.Numeric(precision=15, scale=4), nullable=False, comment='Troco devolvido (apenas dinheiro)'),
    sa.Column('nsu', sa.String(length=20), nullable=True, comment='Número Sequencial Único da transação de cartão'),
    sa.Column('bandeira_cartao', sa.String(length=30), nullable=True, comment='Ex: Visa, Mastercard, Elo, Pix'),
    sa.Column('autorizacao_cartao', sa.String(length=20), nullable=True, comment='Código de autorização da operadora de cartão'),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valor > 0', name='ck_pagamentos_valor_positivo'),
    sa.ForeignKeyConstraint(['empresa_id', 'venda_id'], ['vendas.empresa_id', 'vendas.id'], name='fk_pagamentos_empresa_venda', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Formas de pagamento aplicadas a uma venda (suporte a pagamento misto)'
    )
    op.create_index('ix_pagamentos_venda_forma', 'pagamentos_venda', ['empresa_id', 'forma_pagamento'], unique=False)
    op.create_index('ix_pagamentos_venda_venda_id', 'pagamentos_venda', ['venda_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pagamentos_venda_venda_id', table_name='pagamentos_venda')
    op.drop_index('ix_pagamentos_venda_forma', table_name='pagamentos_venda')
    op.drop_table('pagamentos_venda')
    op.drop_index('ix_itens_venda_venda_id', table_name='itens_venda')
    op.drop_index('ix_itens_venda_produto_id', table_name='itens_venda')
    op.drop_index('ix_itens_venda_produto_data', table_name='itens_venda')
    op.drop_table('itens_venda')
    op.drop_index('uq_doc_fiscal_venda_ativo', table_name='documentos_fiscais', postgresql_where=sa.text("venda_id IS NOT NULL AND status NOT IN ('cancelada', 'rejeitada', 'inutilizada', 'erro')"))
    op.drop_index('ix_doc_fiscal_venda_id', table_name='documentos_fiscais')
    op.drop_index('ix_doc_fiscal_status', table_name='documentos_fiscais')
    op.drop_index('ix_doc_fiscal_pendentes', table_name='documentos_fiscais')
    op.drop_index('ix_doc_fiscal_empresa_id', table_name='documentos_fiscais')
    op.drop_index('ix_doc_fiscal_data_emissao', table_name='documentos_fiscais')
    op.drop_index('ix_doc_fiscal_chave_acesso', table_name='documentos_fiscais')
    op.drop_table('documentos_fiscais')
    op.drop_index('ix_vendas_status', table_name='vendas')
    op.drop_index('ix_vendas_sessao_caixa_id', table_name='vendas')
    op.drop_index('ix_vendas_operador_id', table_name='vendas')
    op.drop_index('ix_vendas_empresa_id', table_name='vendas')
    op.drop_index('ix_vendas_data_venda', table_name='vendas')
    op.drop_table('vendas')
    op.drop_index('ix_produto_eans_produto_id', table_name='produto_eans')
    op.drop_index('ix_produto_eans_ean', table_name='produto_eans')
    op.drop_table('produto_eans')
    op.drop_index('ix_mov_estoque_referencia', table_name='movimentacoes_estoque')
    op.drop_index('ix_mov_estoque_produto_id', table_name='movimentacoes_estoque')
    op.drop_index('ix_mov_estoque_produto_data', table_name='movimentacoes_estoque')
    op.drop_index('ix_mov_estoque_local_id', table_name='movimentacoes_estoque')
    op.drop_index('ix_mov_estoque_empresa_id', table_name='movimentacoes_estoque')
    op.drop_index('ix_mov_estoque_criado_em', table_name='movimentacoes_estoque')
    op.drop_table('movimentacoes_estoque')
    op.drop_index('ix_mov_caixa_sessao_id', table_name='movimentacoes_caixa')
    op.drop_index('ix_mov_caixa_criado_em', table_name='movimentacoes_caixa')
    op.drop_table('movimentacoes_caixa')
    op.drop_index('ix_log_auditoria_usuario_id', table_name='log_auditoria')
    op.drop_index('ix_log_auditoria_tabela_registro', table_name='log_auditoria')
    op.drop_index('ix_log_auditoria_empresa_id', table_name='log_auditoria')
    op.drop_index('ix_log_auditoria_criado_em', table_name='log_auditoria')
    op.drop_index('ix_log_auditoria_acao', table_name='log_auditoria')
    op.drop_table('log_auditoria')
    op.drop_index('ix_estoque_saldo_baixo', table_name='estoque')
    op.drop_index('ix_estoque_local_id', table_name='estoque')
    op.drop_index('ix_estoque_empresa_id', table_name='estoque')
    op.drop_table('estoque')
    op.drop_index('uq_sessao_caixa_aberta', table_name='sessoes_caixa', postgresql_where=sa.text("status = 'aberta'"))
    op.drop_index('ix_sessoes_caixa_status', table_name='sessoes_caixa')
    op.drop_index('ix_sessoes_caixa_operador_id', table_name='sessoes_caixa')
    op.drop_index('ix_sessoes_caixa_caixa_id', table_name='sessoes_caixa')
    op.drop_index('ix_sessoes_caixa_abertura', table_name='sessoes_caixa')
    op.drop_table('sessoes_caixa')
    op.drop_index('ix_produtos_empresa_id', table_name='produtos')
    op.drop_index('ix_produtos_ean_principal', table_name='produtos')
    op.drop_index('ix_produtos_categoria_id', table_name='produtos')
    op.drop_index('ix_produtos_ativo', table_name='produtos')
    op.drop_table('produtos')
    op.drop_index('ix_usuarios_empresa_id', table_name='usuarios')
    op.drop_index('ix_usuarios_email', table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index('ix_unidades_medida_empresa_id', table_name='unidades_medida')
    op.drop_table('unidades_medida')
    op.drop_index('ix_sequencias_fiscais_empresa_id', table_name='sequencias_fiscais')
    op.drop_table('sequencias_fiscais')
    op.drop_index('uq_perfil_tributario_nome_ativo', table_name='perfis_tributarios', postgresql_where=sa.text('ativo = true'))
    op.drop_index('ix_perfil_trib_ncm', table_name='perfis_tributarios')
    op.drop_index('ix_perfil_trib_empresa_ativo', table_name='perfis_tributarios')
    op.drop_table('perfis_tributarios')
    op.drop_index('ix_locais_estoque_empresa_id', table_name='locais_estoque')
    op.drop_table('locais_estoque')
    op.drop_index('ix_categorias_empresa_id', table_name='categorias')
    op.drop_table('categorias')
    op.drop_index('ix_caixas_empresa_id', table_name='caixas')
    op.drop_table('caixas')
    op.drop_table('empresas')
    # ### end Alembic commands ###
